# Copyright 2023 by Alex Utter

[package]
name = "AdventOfCode2017"
version = "0.1.0"
edition = "2021"

[dependencies]
aocfetch = { git = "https://github.com/ooterness/AdventOfCode.git" }
reqwest = { version = "0.11.*", features = ["blocking"] }
